name: Deploy to heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROUK_APP_PRODUCTION}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

    - name: Successful Message
      run: echo Successfully Deployed!!